---
language: generic

sudo: required

services:
  - docker

cache:
  directories:
    - .flatpak-builder

before_script:
  - git clone -b gh-pages https://github.com/$TRAVIS_REPO_SLUG export/ && cp -rf export/repo . || mkdir export

script:
  - docker run --privileged -v ${PWD}:/source -i vrutkovs/flatpak:test make -C source/

before_deploy:
  - rm -rf export && mkdir export
  - cp -rf repo/ export/
  - cp -rf riot.flatpakref export/

deploy:
  provider: pages
  local_dir: export
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
